### ISSUE TITLE
Need fix for the enumlib's repo url. 

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/pymatgen#1788]
Hi,

The following webpage: https://pymatgen.org/installation.html, says that:
```
2. enum: 
Get it at http://enum.sourceforge.net and follow the instructions to compile multienum.x and makestr.x.

```
 
But this project has moved to github in 2015 as noted on the above website:

`(We have migrated this project to github [June 1 2015)] http://github.com/msg-byu/enumlib).`

Could you please fix this?

Regards

**Comment by shyuep** [comment]
Done. Thanks.

**Comment by hongyi-zhao** [comment]
But when I opened the website https://pymatgen.org/installation.html, it still shows the wrong url I reported here.

Regards

**Comment by mkhorton** [comment]
Sometimes it takes a while to update on the website after a change has been made due to the content delivery networks that GitHub Pages uses (which is where pymatgen.org is hosted).

**Comment by shyuep** [comment]
Sorry, there was a problem with the doc generation script. It should now be updated. For future reference, you can easily edit the docs in docs_rst and update the URLs if needed and submit a PR.
